#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2013
#
#############################################################################

# Specify target chip or board or system
TARGET     := lpc810m021fn8

# Specify the location of the bmptk library
BMPTK      := ../../../..

# Specify project files (other than $(PROJECT).*) (if any)
SOURCES    := lpc810lib.c
HEADERS    := lpc810lib.h

# The Makefile.inc does all the work
include $(BMPTK)/Makefile.inc
