#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2015
#
# This file is in the public domain.
# 
#############################################################################

# Specify target chip or board or system
TARGET     := lpc1114fn28

# Specify the location of the bmptk library
BMPTK      := ../../../..

SOURCES := timer.c sw-uart.c
HEADERS := timer.h pins.h sw-uart.h

SEARCH  := ../lib

# The Makefile.inc does all the work
include $(BMPTK)/Makefile.inc